global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["20.40.46.23:8000"]

  - job_name: "node"
    static_configs:
      - targets: ["20.40.46.23:9100"]