import json
import urllib.request
import uuid

# We append a random UUID to the query to guarantee a cache bypass,
# ensuring the response is freshly generated by RunPod.
payload = {
    "generation_id": str(uuid.uuid4()),
    "model": "shubhamprakash108/chartqa-vlm-vllm",
    "image_url": "https://cdn1.byjus.com/wp-content/uploads/2021/03/bar-graph.png",
    "query": "Which colour has the highest graph? (ID: " + str(uuid.uuid4()) + ")"
}

req = urllib.request.Request(
    url="http://20.40.46.23:8000/analyze/stream",
    data=json.dumps(payload).encode("utf-8"),
    headers={
        "X-API-Key": "12345",
        "Content-Type": "application/json"
    },
    method="POST"
)

print(f"Sending Request to RunPod...\nModel: {payload['model']}\nImage: {payload['image_url']}")
print("-" * 50)

try:
    with urllib.request.urlopen(req) as response:
        # The API streams the response chunk by chunk
        for line in response:
            if line:
                # Decode and print exactly as it arrives
                print(line.decode("utf-8"), end="", flush=True)
    print("\n" + "-" * 50)
    print("Stream Completed.")
except Exception as e:
    print("\nFailed!", e)
    if hasattr(e, 'read'):
        print(e.read().decode("utf-8"))
